name: Build kernel deb packages
on: 
 workflow_dispatch: # 仅手动触发

jobs:
  build:
    name: Build kernel
    runs-on: ubuntu-24.04
    container: debian:buster
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build
        run: bash build_action.sh

      - name: Artifact
        uses: actions/upload-artifact@v3
        with:
          name: artifact
          path: ${{ github.workspace }}/artifact/
